<?php
function getPhrases()
{

  $list = array(
    'This book is largely concerned with Hobbits, and from its pages a reader may discover much of their character and a little of their history.',
    'With tgit add .hem he set out, to his own lasting astonishment, on a morning of April, it being then the year 1341 Shire-reckoning, on a quest of great treasure, the dwarf-hoards of the Kings under the Mountain, beneath Erebor in Dale, far off in the East.',
    'The quest was successful, and the Dragon that guarded the hoard was destroyed.',
    'The Shire was divided into four quarters, the Farthings already referred to.',
    'North, South, East, and West; and these again each into a number of folklands, which still bore the names of some of the old leading families, although by the time of this history these names were no longer found only in their proper folklands.',
    'Nearly all Tooks still lived in the Tookland, but that was not true of many other families, such as the Bagginses or the Boffins.',
    'Outside the Farthings were the East and West Marches: the Buckland; and the Westmarch added to the Shire in S. R. 1462.',
    'There remained, of course, the ancient tradition concerning the high king at Fornost, or Norbury as they called it, away north of the Shire.',
    'But there had been no king for nearly a thousand years, and even the ruins of Kings Norbury were covered with grass.',
    'For they attributed to the king of old all their essential laws; and usually they kept the laws of free will, because they were The Rules (as they said), both ancient and just.',
    'Thain had passed to them (from the Oldbucks) some centuries before, and the chief Took had borne that title ever since.',
    'The Thain was the master of the Shire-moot, and captain of the Shire-muster and the Hobbitry-in-arms, but as muster and moot were only held in times of emergency, which no longer occurred, the Thainship had ceased to be more than a nominal dignity.',
    'The Took family was still, indeed, accorded a special respect, for it remained both numerous and exceedingly wealthy, and was liable to produce in every generation strong characters of peculiar habits and even adventurous temperament.',
    'The custom endured, nonetheless, of referring to the head of the family as The Took, and of adding to his name, if required, a number: such as Isengrim the Second, for instance.',
    'The only real official in the Shire at this date was the Mayor of Michel Delving (or of the Shire), who was elected every seven years at the Free Fair on the White Downs at the Lithe, that is at Midsummer.',
    'As mayor almost his only duty was to preside at banquets, given on the Shire-holidays, which occurred at frequent intervals.',
    'But the offices of Postmaster and First Shirriff were attached to the mayoralty, so that he managed both the Messenger Service and the Watch.',
    'These were the only Shire-services, and the Messengers were the most numerous, and much the busier of the two.',
    'The night passed without Gollum showing so much as a shadow again.',
    'After that the Company kept a sharp look-out, but they saw no more of Gollum while the voyage lasted.',
    'At Aragorn’s bidding they paddled now for long spells, and the banks went swiftly by.',
    'But they saw little of the country, for they journeyed mostly by night and twilight, resting by day, and lying as hidden as the land allowed.',
    'It was silent and windless; the grey east wind had passed away.',
    'Hobbits go light, and their footprints are not easy even for a Ranger to read, but not far from the top a spring crossed the path, and in the wet earth he saw what he was seeking.',
    'He desired to go to the high seat himself, hoping to see there something that would guide him in his perplexities; but time was pressing.',
    'The horn of Boromir! he cried. He is in need!',
    'As he ran the cries came louder, but fainter now and desperately the horn was blowing.',
    'Fierce and shrill rose the yells of the Orcs, and suddenly the horn-calls ceased.',
    'Aragorn raced down the last slope, but before he could reach the hills foot, the sounds died away; and as he turned to the left and ran towards them they retreated, until at last he could hear them no more.',
    'Drawing his bright sword and crying Elendil! Elendil! he crashed through the trees.',
    'A mile, maybe, from Parth Galen in a little glade not far from the lake he found Boromir.',
    'He was sitting with his back to a great tree, as if he was resting.',
    'But Aragorn saw that he was pierced with many black-feathered arrows; his sword was still in his hand, but it was broken near the hilt; his horn cloven in two was at his side.',
    'Many Orcs lay slain, piled all about him and at his feet.',
    'Aragorn knelt beside him. Boromir opened his eyes and strove to speak.',
    'At last slow words came. I tried to take the Ring from Frodo, he said. I am sorry. I have paid.',
    'He knelt for a while, bent with weeping, still clasping Boromirs hand.',
    'So it was that Legolas and Gimli found him.',
    'Gimli had his axe in hand, and Legolas his long knife: all his arrows were spent.',
    'When they came into the glade they halted in amazement; and then they stood a moment with heads bowed in grief, for it seemed to them plain what had happened.',
    'We will send him to the Falls of Rauros and give him to Anduin.',
    'I sent him to follow Merry and Pippin; but I did not ask him if Frodo or Sam were with him',
    'We must follow the Orcs, if there is hope that any of our Company are living prisoners.',
    'Quickly they searched the bodies of the Orcs, gathering their swords and cloven helms and shields into a heap.',
    'There were four goblin-soldiers of greater stature, swart, slant-eyed, with thick legs and large hands.',
    'They were armed with short broad-bladed swords, not with the curved scimitars usual with Orcs: and they had bows of yew, in length and shape like the bows of Men.',
    'Upon their shields they bore a strange device: a small white hand in the centre of a black field; on the front of their iron helms was set an S-rune, wrought of some white metal.',
    'There is evil afoot in Isengard, and the West is no longer safe.',
    'It is as Gandalf feared: by some means the traitor Saruman has had news of our journey.',
    'It is likely too that he knows of Gandalf\'s fall. Pursuers from Moria may have escaped the vigilance of Lorien, or they may have avoided that land and come to Isengard by other paths.',
    'Taking his axe the Dwarf now cut several branches.',
    'These they lashed together with bowstrings, and spread their cloaks upon the frame.',
    'Upon this rough bier they carried the body of their companion to the shore, together with such trophies of his last battle as they chose to send forth with him.',
    'It was only a short way, yet they found it no easy task, for Boromir was a man both tall and strong.',
    'At the water-side Aragorn remained, watching the bier, while Legolas and Gimli hastened back on foot to Parth Galen.',
    'It was a mile or more, and it was some time before they came back, paddling two boats swiftly along the shore.',
    'Now they laid Boromir in the middle of the boat that was to bear him away.',
    'Sorrowfully they cast loose the funeral boat: there Boromir lay, restful, peaceful, gliding upon the bosom of the flowing water.',
    'The stream took him while they held their own boat back with their paddles.',
    'And unless there is much amiss in Rohan and the power of Saruman is greatly increased; they will take the shortest way that they can find over the fields of the Rohirrim.',
    'Below it twenty fathoms or more, there was a wide and rugged shelf which ended suddenly in the brink of a sheer cliff: the East Wall of Rohan.',
    'It was in forgotten years long ago that Eorl the Young brought them out of the North, and their kinship is rather with the Bardings of Dale, and with the Beornings of the Wood, among whom may still be seen many men tall and fair, as are the Riders of Rohan.',
    'At length even Gimli could hear the distant beat of galloping hoofs.',
    'The horsemen, following the trail, had turned from the river, and were drawing near the downs.',
    'Now the cries of clear strong voices came ringing over the fields.',
    'Suddenly they swept up with a noise like thunder, and the foremost horseman swerved, passing by the foot of the hill, and leading the host back southward along the western skirts of the downs.',
    'After him they rode: a long line of mail-clad men, swift, shining, fell and fair to look upon.',
    'Their horses were of great stature, strong and clean-limbed; their grey coats glistened, their long tails flowed in the wind, their manes were braided on their proud necks.',
    'The Men that rode them matched them well: tall and long-limbed; their hair, flaxen-pale, flowed under their light helms, and streamed in long braids behind them; their faces were stern and keen.',
    'In their hands were tall spears of ash, painted shields were slung at their backs, long swords were at their belts, their burnished skirts of mail hung down upon their knees.',
    'In pairs they galloped by, and though every now and then one rose in his stirrups and gazed ahead and to either side, they appeared not to perceive the three strangers sitting silently and watching them.',
    'The host had almost passed when suddenly Aragorn stood up, and called in a loud voice:',
    'What news from the North, Riders of Rohan?',
    'With astonishing speed and skill they checked their steeds, wheeled, and came charging round.',
    'Soon the three companions found themselves in a ring of horsemen moving in a running circle, up the hill-slope behind them and down, round and round them, and drawing ever inwards.',
    'Aragorn stood silent, and the other two sat without moving, wondering what way things would turn.',
    'Without a word or cry, suddenly, the Riders halted.',
    'A thicket of spears were pointed towards the strangers; and some of the horsemen had bows in hand, and their arrows were already fitted to the string.',
    'Then one rode forward, a tall man, taller than all the rest; from his helm as a crest a white horsetail flowed.',
    'He advanced until the point of his spear was within a foot of Aragorn\'s breast.',
    'Who are you, and what are you doing in this land?',
    'I am called Strider,\' answered Aragorn. \'I came out of the North. I am hunting Orcs.\'',
    'The Rider leaped from his horse. Giving his spear to another who rode up and dismounted at his side, he drew his sword and stood face to face with Aragorn, surveying him keenly, and not without wonder.',
    'At first I thought that you yourselves were Orcs,\' he said, \'but now I see that it is not so.',
    'Indeed you know little of Orcs, if you go hunting them in this fashion.',
    'They were swift and well-armed, and they were many.',
    'You would have changed from hunters to prey, if ever you had overtaken them.',
    'But there is something strange about you, Strider.',
    'He bent his clear bright eyes again upon the Ranger.',
    'That is no name for a Man that you give. And strange too is your raiment.',
    'Have you sprung out of the grass? How did you escape our sight? Are you elvish folk?',
    '\'No,\' said Aragorn. \'One only of us is an Elf, Legolas from the Woodland Realm in distant Mirkwood.',
    'But we have passed through Lothlorien, and the gifts and favour of the Lady go with us.',
    'The Rider looked at them with renewed wonder, but his eyes hardened.',
    'he said. \'Few escape her nets, they say. These are strange days! But if you have her favour, then you also are net-weavers and sorcerers, maybe.\'',
    'He turned a cold glance suddenly upon Legolas and Gimli. \'Why do you not speak, silent ones?\' he demanded.',
    'Gimli rose and planted his feet firmly apart: his hand gripped the handle of his axe, and his dark eyes flashed. \'Give me your name, horse-master, and I will give you mine, and more besides,\' he said.',
    'As for that,\' said the Rider, staring down at the Dwarf, \'the stranger should declare himself first.',
    'Yet I am named Eomer son of Eomund, and am called the Third Marshal of Riddermark.',
    'Then Eomer son of Eomund, Third Marshal of Riddermark, let Gimli the Dwarf Gloin\'s son warn you against foolish words.',
    'Eomer\'s eyes blazed, and the Men of Rohan murmured angrily, and closed in, advancing their spears.',
    '\'I would cut off your head, beard and all, Master Dwarf, if it stood but a little higher from the ground,\' said Eomer.',
    '\'He stands not alone,\' said Legolas, bending his bow and fitting an arrow with hands that moved quicker than sight. \'You would die before your stroke fell.\'',
    'Eomer raised his sword, and things might have gone ill, but Aragorn sprang between them, and raised his hand.',
    '\'First tell me whom you serve,\' said Aragorn. \'Are you friend or foe of Sauron, the Dark Lord of Mordor?\'',
    '\'I serve only the Lord of the Mark, Theoden King son of Thengel,\' answered Eomer.',
    );
  return $list;
}
